### ISSUE TITLE
Generator failed to npm install v 2.1.0

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#62]
1. execute command `yo adaptiveme adaptive-sample-app2 latest false none android,ios --ios-version 8.1 --android-version 5.0 --skip-install --skip-cache`
2. execute command `npm install`

**current folder** `/tmp/gen-test`
error:

```
pm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "gen test"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:234:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /tmp/gen-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/gen-test/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Panthro** [comment]
probably related to #61

**Comment by Panthro** [comment]
```
npm -v
1.3.10
node --version
v0.10.25
```

**Comment by Panthro** [comment]
package.json

```
{
  "name": "gen test",
  "title": "gen test",
  "version": "0.0.1",
  "description": "Description for gen test",
  "license": "Apache-2.0",
  "repository": {
    "type": "",
    "url": ""
  },
```
