### ISSUE TITLE
Error generating project with "Initializr Boostrap" 

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#64]
1. `yo adaptiveme adaptivesampleapp latest false "Initializr Boostrap" android,ios --ios-version 8.1 --android-version 5.0 --skip-install --skip-cache`

output:

```
[generator-adaptive] Starting generator...
[generator-adaptive] Saving configurations and configure the project...
[generator-adaptive] Copying application folders and files...

events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token ILLEGAL in /usr/local/lib/node_modules/generator-adaptiveme/generators/app/templates/src/boostrap/fonts/glyphicons-halflings-regular.ttf while compiling ejs
    at Object.Function (<anonymous>)
    at Object.Template.compile (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:460:12)
    at Object.compile (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:288:16)
    at handleCache (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:147:16)
    at Object.exports.render (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:315:10)
    at copy.process (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:56:24)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-adaptiveme/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
```

**Comment by Panthro** [comment]
Confirmed with boilerplate `"Initializr Responsive"` as well

**Comment by ferranvila** [comment]
`yo adaptiveme adaptivesampleapp latest false "Initializr Responsive" android,ios --ios-version 8.1 --android-version 5.0 --skip-install --skip-cache`

Works for me :smile:
